# Generated by Django 4.1.2 on 2022-10-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['text'], 'ordering': ['-pub_date']},
        ),
    ]
